FROM ubuntu:22.04

USER root

ENV DEBIAN_FRONTEND=noninteractive 

COPY scripts/setup_ros.sh setup_ros.sh
COPY scripts/setup_repository.sh setup_repository.sh

# Install ROS dependencies
RUN ./setup_ros.sh

WORKDIR /root/bur-onboard
RUN ./setup_repository.sh

CMD cd /root/bur-onboard/ros2_ws
ENTRYPOINT /bin/bash
