bur_autonomy:
  ros__parameters:
    localizer_topic: "/odometry/filtered"
    vision_topic: "/vision"
    
    goal_topic: "/des_pose"
    joy_topic: "/joy"
    pub_rate: 10

    behavior_tree: "manager.launch.py should replace me"
    tick_rate: 10

    shutdown_on_end: true
    wait_for_depth: false

    start_position:
      x: 0.0
      y: 0.0
      z: 0.0

    gate_target:
      x: 20.0
      y: 0.0
      z: 0.0
    
    buoy_position:
      x: 10.0
      y: 10.0
      z: 0.0
