#!/bin/bash

set -o pipefail
let restarts=1
while true; do
    exec 5>&2
    msg=$(colcon build --symlink-install $@ 3>&2 2>&1 1>&3 | tee /dev/fd/5)
    exit_code=$?
    if [ $exit_code -eq "0" ] || ! [[ $msg =~  "Killed signal terminated program cc1plus" ]]; then
        (exit "$exit_code")
        break
    else
        echo -e "\n\e[32m[INFO] \e[00mOOM SIGKILL detected, restarting... (# restarts: $restarts)\e[0m\n"
        let restarts++
    fi
done

ROS_INSTALL_PATH="$(pwd)/install/setup.bash"
source ${ROS_INSTALL_PATH}
grep -F "source ${ROS_INSTALL_PATH}" ~/.bashrc \
    || echo "source ${ROS_INSTALL_PATH}" >> ~/.bashrc

